$path='\\192.168.231.8\CE Internal\4. CE WEEKLY REPORT\Mold List (禮拜五下班前)\mold_dashboard.html'
$content = Get-Content -LiteralPath $path -Raw

$content = $content.Replace('.card{padding:18px 18px 16px}.card-label{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:10px}.card-value{font-size:34px;font-weight:800;letter-spacing:-.04em;margin-bottom:6px}.card-note{color:var(--muted);font-size:13px;line-height:1.5}','.card{padding:18px 18px 16px}.card-label{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:10px}.card-value{font-size:34px;font-weight:800;letter-spacing:-.04em;margin-bottom:8px}.card-note{color:var(--muted);font-size:13px;line-height:1.5}.card-breakdown{display:flex;gap:14px;flex-wrap:wrap;margin-top:10px;padding-top:10px;border-top:1px solid rgba(24,33,38,.08)}.card-breakdown span{font-size:12px;color:var(--muted)}.card-breakdown strong{color:var(--ink);font-size:13px}')

$content = $content.Replace('<section class="hero"><div class="hero-panel"><div class="eyebrow">Weekly Mold View</div><h1>Mold List Dashboard</h1></div><div class="summary-panel"><div class="summary-title">Overview</div><p class="summary-copy">Brand-level comparison stays here, while the cards below show overall totals and follow-up items without repeating the same numbers.</p><table class="summary-table"><thead><tr><th>Brand</th><th>Active</th><th>EOL</th><th>Shipped</th><th>Fab</th><th>Stop</th></tr></thead><tbody><tr><td>Daewon Mold</td><td>207</td><td>9</td><td>5</td><td>5</td><td>1</td></tr><tr><td>Peak Mold</td><td>341</td><td>6</td><td>48</td><td>10</td><td>7</td></tr></tbody></table></div></section>','<section class="hero"><div class="hero-panel"><div class="eyebrow">Weekly Mold View</div><h1>Mold List Dashboard</h1></div><div class="summary-panel"><div class="summary-title">Overview</div><p class="summary-copy">All key numbers are summarized below as large cards. Each card shows the total first, then a small DW / Peak split underneath.</p></div></section>')

$content = $content.Replace("var cardConfig=[{key:'All',label:'Total Molds',note:'All saved records'},{key:'In Production',label:'In Production',note:'Currently in production'},{key:'TF by TW',label:'TF by TW',note:'TW transfer-related molds'},{key:'Transfer Mold',label:'Transfer Mold',note:'Transfer mold status'},{key:'Coating Required',label:'Coating Required',note:'Need coating action'},{key:'Coating In Progress',label:'Coating In Progress',note:'Coating already underway'}];","var cardConfig=[{key:'All',label:'Total Molds',note:'All saved records'},{key:'In Production',label:'Active',note:'Currently in production'},{key:'EOL',label:'EOL',note:'Ended or replaced molds'},{key:'Shipped Out',label:'Shipped',note:'Shipped out molds'},{key:'Fabrication In Progress',label:'Fab In Progress',note:'Currently under fabrication'},{key:'Stop Fabrication',label:'Stop Fabrication',note:'Stopped fabrication items'},{key:'TF by TW',label:'TF by TW',note:'TW transfer-related molds'},{key:'Transfer Mold',label:'Transfer Mold',note:'Transfer mold status'},{key:'Coating Required',label:'Coating Required',note:'Need coating action'},{key:'Coating In Progress',label:'Coating In Progress',note:'Coating already underway'}];")

$old = @"
function countByStatus(key){var i,c=0; if(key==='All') return rows.length; for(i=0;i<rows.length;i++){ if(key==='Coating Required' && text(rows[i].coatingCheck)==='Progress Required') c++; else if(key==='Coating In Progress' && text(rows[i].coatingCheck)==='In Progress') c++; else if(rows[i].keyStatus===key) c++; } return c; }
function renderCards(){var html='', i, card; for(i=0;i<cardConfig.length;i++){card=cardConfig[i]; html += '<article class="card"><div class="card-label">'+htmlEscape(card.label)+'</div><div class="card-value">'+countByStatus(card.key)+'</div><div class="card-note">'+htmlEscape(card.note)+'</div></article>'; } cardsEl.innerHTML=html;}
"@
$new = @"
function cardBrandGroup(row){return text(row.brand)==='Daewon'?'DW':'Peak';}
function countByStatus(key, brandGroup){var i,c=0, group; for(i=0;i<rows.length;i++){group=cardBrandGroup(rows[i]); if(brandGroup && group!==brandGroup){continue;} if(key==='All'){ c++; } else if(key==='Coating Required' && text(rows[i].coatingCheck)==='Progress Required'){ c++; } else if(key==='Coating In Progress' && text(rows[i].coatingCheck)==='In Progress'){ c++; } else if(rows[i].keyStatus===key){ c++; }} return c; }
function renderCards(){var html='', i, card, total, dw, peak; for(i=0;i<cardConfig.length;i++){card=cardConfig[i]; total=countByStatus(card.key); dw=countByStatus(card.key,'DW'); peak=countByStatus(card.key,'Peak'); html += '<article class="card"><div class="card-label">'+htmlEscape(card.label)+'</div><div class="card-value">'+total+'</div><div class="card-note">'+htmlEscape(card.note)+'</div><div class="card-breakdown"><span>DW <strong>'+dw+'</strong></span><span>Peak <strong>'+peak+'</strong></span></div></article>'; } cardsEl.innerHTML=html;}
"@
$content = $content.Replace($old, $new)

Set-Content -LiteralPath $path -Value $content -Encoding UTF8
