$path='\\192.168.231.8\CE Internal\4. CE WEEKLY REPORT\Mold List (禮拜五下班前)\mold_dashboard.html'
$content = Get-Content -LiteralPath $path -Raw

$oldCss = '.message.ok{color:var(--accent)}.message.warn{color:#8f3d09}.table-panel{overflow:hidden}'
$newCss = '.message.ok{color:var(--accent)}.message.warn{color:#8f3d09}.message.dup{color:#b42318}.field.duplicate label{color:#b42318}.field.duplicate input{border-color:#b42318;background:#fff1f1;color:#b42318}.duplicate-text{color:#b42318;font-weight:700}.table-panel{overflow:hidden}'
$content = $content.Replace($oldCss,$newCss)

$oldSetMessage = "function setMessage(message, kind){entryMessage.className='message ' + (kind||''); entryMessage.innerHTML=htmlEscape(message||'');}"
$newSetMessage = @"function setMessage(message, kind){entryMessage.className='message ' + (kind||''); entryMessage.innerHTML=htmlEscape(message||'');}
function normalizeSlipLockValue(v){return text(v).replace(/\s+/g,'').toUpperCase();}
function isMeaningfulSlipLockValue(v){var n=normalizeSlipLockValue(v); return !!n && n!=='.' && n!=='NONE' && n!=='N/A';}
function findSlipLockDuplicateIndex(value, ignoreIndex){var needle=normalizeSlipLockValue(value), i; if(!isMeaningfulSlipLockValue(needle)) return -1; for(i=0;i<rows.length;i++){ if(i===ignoreIndex) continue; if(isMeaningfulSlipLockValue(rows[i].slipLock) && normalizeSlipLockValue(rows[i].slipLock)===needle){ return i; }} return -1;}
function updateSlipLockWarning(){var slipInput=byId('entrySlipLock'), field=slipInput.parentNode, dupIndex=findSlipLockDuplicateIndex(slipInput.value, editIndex); field.className = dupIndex>-1 ? 'field duplicate' : 'field'; if(dupIndex>-1){ setMessage('Duplicate Slip Lock with '+text(rows[dupIndex].moldNo)+'.', 'dup'); } else if(entryMessage.className==='message dup'){ setMessage('', ''); } return dupIndex;}
"@
$content = $content.Replace($oldSetMessage, $newSetMessage.Trim())

$oldRender = "<td>'+htmlEscape(row.designType)+'</td><td>'+htmlEscape(row.slipLock)+'</td><td>'+htmlEscape(row.heatTreatCore)+'</td>"
$newRender = "<td>'+htmlEscape(row.designType)+'</td><td class='+(findSlipLockDuplicateIndex(row.slipLock,item.index)>-1?'\"duplicate-text\"':'\"\"')+'>'+htmlEscape(row.slipLock)+'</td><td>'+htmlEscape(row.heatTreatCore)+'</td>"
$content = $content.Replace($oldRender,$newRender)

$oldClear = "function clearForm(){byId('entryBrand').value='Daewon'; byId('entryMoldNo').value=''; byId('entrySapMoldNo').value=''; byId('entryRevision').value=''; byId('entryDescription').value=''; byId('entryCustomer').value=''; byId('entryOrigin').value=''; byId('entrySitePn').value=''; byId('entryDate').value=''; byId('entryTrayWeight').value=''; byId('entryMaterialDwg').value=''; byId('entryMaterialProduction').value=''; byId('entryMatrix').value=''; byId('entryCellCount').value=''; byId('entryZGap').value=''; byId('entryDesignType').value=''; byId('entrySlipLock').value=''; byId('entryHeatTreatCore').value='No'; byId('entryCoatingCheck').value='Progress Required'; byId('entryStatus').value='In Production';}"
$newClear = "function clearForm(){byId('entryBrand').value='Daewon'; byId('entryMoldNo').value=''; byId('entrySapMoldNo').value=''; byId('entryRevision').value=''; byId('entryDescription').value=''; byId('entryCustomer').value=''; byId('entryOrigin').value=''; byId('entrySitePn').value=''; byId('entryDate').value=''; byId('entryTrayWeight').value=''; byId('entryMaterialDwg').value=''; byId('entryMaterialProduction').value=''; byId('entryMatrix').value=''; byId('entryCellCount').value=''; byId('entryZGap').value=''; byId('entryDesignType').value=''; byId('entrySlipLock').value=''; byId('entrySlipLock').parentNode.className='field'; byId('entryHeatTreatCore').value='No'; byId('entryCoatingCheck').value='Progress Required'; byId('entryStatus').value='In Production';}"
$content = $content.Replace($oldClear,$newClear)

$oldOpen = "function openEditor(mode, index){editorPanel.className='editor-panel open'; editIndex=(typeof index==='number')?index:-1; setMessage('', ''); if(mode==='edit' && index>-1){var row=rows[index]; if(/^peak$/i.test(text(row.origin))){ row.origin='SZ'; } editorTitle.innerHTML='Edit Product'; byId('entryBrand').value=text(row.brand)||'Daewon'; byId('entryMoldNo').value=text(row.moldNo); byId('entrySapMoldNo').value=text(row.sapMoldNo); byId('entryRevision').value=text(row.rev); byId('entryDescription').value=text(row.description); byId('entryCustomer').value=text(row.customer); byId('entryOrigin').value=text(row.origin); byId('entrySitePn').value=text(row.sitePn); byId('entryDate').value=text(row.registrationDate); byId('entryTrayWeight').value=text(row.trayWeight); byId('entryMaterialDwg').value=text(row.materialDwg); byId('entryMaterialProduction').value=text(row.materialProduction); byId('entryMatrix').value=text(row.matrix); byId('entryCellCount').value=text(row.cellCount); byId('entryZGap').value=text(row.zGap); byId('entryDesignType').value=text(row.designType); byId('entrySlipLock').value=text(row.slipLock); byId('entryHeatTreatCore').value=text(row.heatTreatCore)||'No'; byId('entryCoatingCheck').value=text(row.coatingCheck); byId('entryStatus').value=text(row.keyStatus)||'In Production'; } else { editorTitle.innerHTML='Add Product'; clearForm(); } }"
$newOpen = "function openEditor(mode, index){editorPanel.className='editor-panel open'; editIndex=(typeof index==='number')?index:-1; setMessage('', ''); if(mode==='edit' && index>-1){var row=rows[index]; if(/^peak$/i.test(text(row.origin))){ row.origin='SZ'; } editorTitle.innerHTML='Edit Product'; byId('entryBrand').value=text(row.brand)||'Daewon'; byId('entryMoldNo').value=text(row.moldNo); byId('entrySapMoldNo').value=text(row.sapMoldNo); byId('entryRevision').value=text(row.rev); byId('entryDescription').value=text(row.description); byId('entryCustomer').value=text(row.customer); byId('entryOrigin').value=text(row.origin); byId('entrySitePn').value=text(row.sitePn); byId('entryDate').value=text(row.registrationDate); byId('entryTrayWeight').value=text(row.trayWeight); byId('entryMaterialDwg').value=text(row.materialDwg); byId('entryMaterialProduction').value=text(row.materialProduction); byId('entryMatrix').value=text(row.matrix); byId('entryCellCount').value=text(row.cellCount); byId('entryZGap').value=text(row.zGap); byId('entryDesignType').value=text(row.designType); byId('entrySlipLock').value=text(row.slipLock); byId('entryHeatTreatCore').value=text(row.heatTreatCore)||'No'; byId('entryCoatingCheck').value=text(row.coatingCheck); byId('entryStatus').value=text(row.keyStatus)||'In Production'; updateSlipLockWarning(); } else { editorTitle.innerHTML='Add Product'; clearForm(); updateSlipLockWarning(); } }"
$content = $content.Replace($oldOpen,$newOpen)

$oldSave = "byId('saveEntry').onclick=function(){var record=buildRecord(); if(!record){setMessage('Mold No and Description are required.', 'warn'); return;} if(editIndex>-1){rows[editIndex]=record; setMessage('Product updated.', 'ok');} else {rows.unshift(record); setMessage('Product added.', 'ok');} saveRows(); sync(); closeEditor();};"
$newSave = "byId('entrySlipLock').oninput=function(){ updateSlipLockWarning(); }; byId('saveEntry').onclick=function(){var record=buildRecord(), dupIndex; if(!record){setMessage('Mold No and Description are required.', 'warn'); return;} dupIndex=findSlipLockDuplicateIndex(record.slipLock, editIndex); if(editIndex>-1){rows[editIndex]=record;} else {rows.unshift(record);} saveRows(); sync(); if(dupIndex>-1){setMessage('Duplicate Slip Lock with '+text(rows[dupIndex].moldNo)+'. Saved and highlighted in red.', 'dup'); openEditor('edit', editIndex>-1 ? editIndex : 0); return;} setMessage(editIndex>-1 ? 'Product updated.' : 'Product added.', 'ok'); closeEditor();};"
$content = $content.Replace($oldSave,$newSave)

Set-Content -LiteralPath $path -Value $content -Encoding UTF8
Write-Output 'SLIPLOCK_DUP_WARNING_ADDED'
